name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
      versionCode:
        description: 'Version number (50500)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Change version number and name
      run: printf 'ext.version_code = ${{ github.event.inputs.versionCode }}\next.version_name = "${{ github.event.inputs.versionName }}"\n' > app_versions.gradle
    - name: Commit manifest files
      id: make-commit
      run: |
        git add app_versions.gradle
        git commit --message "Prepare release ${{ github.event.inputs.versionName }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}
    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
          head: release/v${{ github.event.inputs.versionName }}
          base: master
          title: "v${{ github.event.inputs.versionName }} into main"
    - name: Create pull request to develop
      uses: thomaseizinger/create-pull-request@1.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
          head: release/v${{ github.event.inputs.versionName }}
          base: develop
          title:  "v${{ github.event.inputs.versionName }} into develop"
