name: Tag Release
on:
  push:
    branches: [ master ]
jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Setup release information
        #get version name from app_versions.gradle file (5.6.2)
        run: |
          versionName=`sed '2q;d' app_versions.gradle | cut -d "=" -f2 | xargs`
          echo "VERSION_NAME=$versionName" >> $GITHUB_ENV
      - name: Extract release notes
        run: |
          release_note=`sed '1q;d' app_versions.gradle | cut -d "=" -f2 | xargs`
          echo "RELEASE_NOTE=$release_note" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ env.VERSION_NAME }}
          release_name: v${{ env.VERSION_NAME }}
          body: ${{ env.RELEASE_NOTE }}
          draft: false
          prerelease: false